### ISSUE TITLE
Using ingress deletes all existing virtual servers and real server pools

### ISSUE THREAD

**Issue by haught** [fortinet/fortiadc-ingress#11]
FortiADCIngressController: 2.0.0 (fortinet/fortiadc-ingress:2.0.0)
FortiADC-2000F v7.4.0,build0308,230706 (GA)

Adding an ingress will **remove all existing virtual servers and real server pools on the load balancer/vdom**!

The ingress is using the *POST /api/declarative* API route and it appears it is declarative for the entire load balancer/vdom and as such will try to remove all existing entries.

Looking at the API calls, the result of those /api/declarative calls results various in "payload" errors, yet the load balancer is creating a working virtual server/content routing/real server pools. Other entries created by the ingress are not removed. Only the manually created entries are being removed. I captured a request when adding an ingress and manually ran the API call with the "async" option set to false (gives text errors) and got this payload:
```json
{
    "payload": [
        "Failed to delete content routing 'test2_test2-ingress_service2_1': Entry is used.",
        "Failed to delete content routing 'test2_test2-ingress_service1_2': Entry is used.",
        "Failed to delete content routing 'test_verify-ingress_verify-purple-service': Entry is used.",
        "Failed to delete content routing 'test_verify-ingress_verify-purple-service_1': Entry is used.",
        "Failed to delete content routing 'test_verify-ingress_verify-green-service_2': Entry is used.",
        "Failed to delete content routing 'test_verify-ingress_verify-blue-service_3': Entry is used.",
        "Failed to delete content routing 'test3_test3-ingress_test3-kuard-service': Entry is used.",
        "Failed to delete real server pool 'test2_service1': Entry is used.",
        "Failed to delete real server pool 'test2_service2': Entry is used.",
        "Failed to delete real server pool 'test_verify-purple-service': Entry is used.",
        "Failed to delete real server pool 'test_verify-blue-service': Entry is used.",
        "Failed to delete real server pool 'test_verify-green-service': Entry is used.",
        "Failed to delete real server pool 'test3_test3-kuard-service': Entry is used."
    ]
}
```
So it appears it is actually **trying** to delete the other ingress created entries but is being denied by the load balancer due to the lb seeing them as being *used*. 

This behavior removed about 30 virtual servers in root on a lab fortiadc 200 instance and dozen in a vdom on a lab fortiadc 2000 instance. I have further confirmed this behavior while rebuilding those.

**Comment by ytlai** [comment]
Hi Matt,

This is the main design of ingress controller 2.0. Ingress controller takes the main control of vs, rs and other ingress related objects. This means on FAD you will only see vs, rs and other ingress related objects that is deployed on k8s side. We use declarative api call to make the synchronization and other manually created objects will be removed since they are not deployed on k8s side.

We will add a warning for customers on 2.0.0 document.
